version: '3'
services:
  app:
    container_name: "foode_web"
    build:
      context: ./
#    volumes:
#      - .:/var/www/html
    ports:
      - "80:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=false